#############################################################################
# Makefile for building: tslimx2simulator
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  tslimx2.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile tslimx2.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = tslimx2simulator1.0.0
DISTDIR = /home/student/Documents/3004/test\ 2.0/.tmp/tslimx2simulator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		testpanel.cpp \
		forceresizable.cpp \
		models/pumpmodel.cpp \
		models/profilemodel.cpp \
		models/glucosemodel.cpp \
		models/insulinmodel.cpp \
		views/homescreen.cpp \
		views/bolusscreen.cpp \
		views/profilescreen.cpp \
		views/optionsscreen.cpp \
		views/graphview.cpp \
		views/historyscreen.cpp \
		views/controliqscreen.cpp \
		views/alertsscreen.cpp \
		views/pinlockscreen.cpp \
		views/pinsettingsscreen.cpp \
		controllers/pumpcontroller.cpp \
		controllers/boluscontroller.cpp \
		controllers/alertcontroller.cpp \
		controllers/profilecontroller.cpp \
		utils/datastorage.cpp \
		utils/errorhandler.cpp \
		utils/controliqalgorithm.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_testpanel.cpp \
		moc_forceresizable.cpp \
		moc_pumpmodel.cpp \
		moc_profilemodel.cpp \
		moc_glucosemodel.cpp \
		moc_insulinmodel.cpp \
		moc_homescreen.cpp \
		moc_bolusscreen.cpp \
		moc_profilescreen.cpp \
		moc_optionsscreen.cpp \
		moc_graphview.cpp \
		moc_historyscreen.cpp \
		moc_controliqscreen.cpp \
		moc_alertsscreen.cpp \
		moc_pinlockscreen.cpp \
		moc_pinsettingsscreen.cpp \
		moc_pumpcontroller.cpp \
		moc_boluscontroller.cpp \
		moc_alertcontroller.cpp \
		moc_profilecontroller.cpp \
		moc_datastorage.cpp \
		moc_errorhandler.cpp \
		moc_controliqalgorithm.cpp
OBJECTS       = main.o \
		mainwindow.o \
		testpanel.o \
		forceresizable.o \
		pumpmodel.o \
		profilemodel.o \
		glucosemodel.o \
		insulinmodel.o \
		homescreen.o \
		bolusscreen.o \
		profilescreen.o \
		optionsscreen.o \
		graphview.o \
		historyscreen.o \
		controliqscreen.o \
		alertsscreen.o \
		pinlockscreen.o \
		pinsettingsscreen.o \
		pumpcontroller.o \
		boluscontroller.o \
		alertcontroller.o \
		profilecontroller.o \
		datastorage.o \
		errorhandler.o \
		controliqalgorithm.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_testpanel.o \
		moc_forceresizable.o \
		moc_pumpmodel.o \
		moc_profilemodel.o \
		moc_glucosemodel.o \
		moc_insulinmodel.o \
		moc_homescreen.o \
		moc_bolusscreen.o \
		moc_profilescreen.o \
		moc_optionsscreen.o \
		moc_graphview.o \
		moc_historyscreen.o \
		moc_controliqscreen.o \
		moc_alertsscreen.o \
		moc_pinlockscreen.o \
		moc_pinsettingsscreen.o \
		moc_pumpcontroller.o \
		moc_boluscontroller.o \
		moc_alertcontroller.o \
		moc_profilecontroller.o \
		moc_datastorage.o \
		moc_errorhandler.o \
		moc_controliqalgorithm.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tslimx2.pro mainwindow.h \
		testpanel.h \
		forceresizable.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		views/homescreen.h \
		views/bolusscreen.h \
		views/profilescreen.h \
		views/optionsscreen.h \
		views/graphview.h \
		views/historyscreen.h \
		views/controliqscreen.h \
		views/alertsscreen.h \
		views/pinlockscreen.h \
		views/pinsettingsscreen.h \
		controllers/pumpcontroller.h \
		controllers/boluscontroller.h \
		controllers/alertcontroller.h \
		controllers/profilecontroller.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		utils/controliqalgorithm.h main.cpp \
		mainwindow.cpp \
		testpanel.cpp \
		forceresizable.cpp \
		models/pumpmodel.cpp \
		models/profilemodel.cpp \
		models/glucosemodel.cpp \
		models/insulinmodel.cpp \
		views/homescreen.cpp \
		views/bolusscreen.cpp \
		views/profilescreen.cpp \
		views/optionsscreen.cpp \
		views/graphview.cpp \
		views/historyscreen.cpp \
		views/controliqscreen.cpp \
		views/alertsscreen.cpp \
		views/pinlockscreen.cpp \
		views/pinsettingsscreen.cpp \
		controllers/pumpcontroller.cpp \
		controllers/boluscontroller.cpp \
		controllers/alertcontroller.cpp \
		controllers/profilecontroller.cpp \
		utils/datastorage.cpp \
		utils/errorhandler.cpp \
		utils/controliqalgorithm.cpp
QMAKE_TARGET  = tslimx2simulator
DESTDIR       = 
TARGET        = tslimx2simulator


first: all
####### Build rules

tslimx2simulator: ui_mainwindow.h ui_homescreen.h ui_bolusscreen.h ui_profilescreen.h ui_optionsscreen.h ui_historyscreen.h ui_controliqscreen.h ui_pinlockscreen.h ui_alertsscreen.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tslimx2.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		tslimx2.pro \
		resources.qrc
	$(QMAKE) -o Makefile tslimx2.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
tslimx2.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile tslimx2.pro

qmake_all: FORCE


all: Makefile tslimx2simulator

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h testpanel.h forceresizable.h models/pumpmodel.h models/profilemodel.h models/glucosemodel.h models/insulinmodel.h views/homescreen.h views/bolusscreen.h views/profilescreen.h views/optionsscreen.h views/graphview.h views/historyscreen.h views/controliqscreen.h views/alertsscreen.h views/pinlockscreen.h views/pinsettingsscreen.h controllers/pumpcontroller.h controllers/boluscontroller.h controllers/alertcontroller.h controllers/profilecontroller.h utils/datastorage.h utils/errorhandler.h utils/controliqalgorithm.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp testpanel.cpp forceresizable.cpp models/pumpmodel.cpp models/profilemodel.cpp models/glucosemodel.cpp models/insulinmodel.cpp views/homescreen.cpp views/bolusscreen.cpp views/profilescreen.cpp views/optionsscreen.cpp views/graphview.cpp views/historyscreen.cpp views/controliqscreen.cpp views/alertsscreen.cpp views/pinlockscreen.cpp views/pinsettingsscreen.cpp controllers/pumpcontroller.cpp controllers/boluscontroller.cpp controllers/alertcontroller.cpp controllers/profilecontroller.cpp utils/datastorage.cpp utils/errorhandler.cpp utils/controliqalgorithm.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui views/homescreen.ui views/bolusscreen.ui views/profilescreen.ui views/optionsscreen.ui views/historyscreen.ui views/controliqscreen.ui views/pinlockscreen.ui views/alertsscreen.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		images/battery-half.png \
		images/battery-full.png \
		images/insulin-full.png \
		images/insulin-half.png \
		images/bolus-icon.png \
		images/logo.png \
		images/battery-low.png \
		images/arrow-down.png \
		images/settings-icon.png \
		images/insulin-low.png \
		images/options-icon.png \
		images/arrow-up.png \
		images/arrow-flat.png \
		styles/dark-style.qss
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_testpanel.cpp moc_forceresizable.cpp moc_pumpmodel.cpp moc_profilemodel.cpp moc_glucosemodel.cpp moc_insulinmodel.cpp moc_homescreen.cpp moc_bolusscreen.cpp moc_profilescreen.cpp moc_optionsscreen.cpp moc_graphview.cpp moc_historyscreen.cpp moc_controliqscreen.cpp moc_alertsscreen.cpp moc_pinlockscreen.cpp moc_pinsettingsscreen.cpp moc_pumpcontroller.cpp moc_boluscontroller.cpp moc_alertcontroller.cpp moc_profilecontroller.cpp moc_datastorage.cpp moc_errorhandler.cpp moc_controliqalgorithm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_testpanel.cpp moc_forceresizable.cpp moc_pumpmodel.cpp moc_profilemodel.cpp moc_glucosemodel.cpp moc_insulinmodel.cpp moc_homescreen.cpp moc_bolusscreen.cpp moc_profilescreen.cpp moc_optionsscreen.cpp moc_graphview.cpp moc_historyscreen.cpp moc_controliqscreen.cpp moc_alertsscreen.cpp moc_pinlockscreen.cpp moc_pinsettingsscreen.cpp moc_pumpcontroller.cpp moc_boluscontroller.cpp moc_alertcontroller.cpp moc_profilecontroller.cpp moc_datastorage.cpp moc_errorhandler.cpp moc_controliqalgorithm.cpp
moc_mainwindow.cpp: mainwindow.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		views/homescreen.h \
		views/graphview.h \
		views/bolusscreen.h \
		views/profilescreen.h \
		views/optionsscreen.h \
		views/historyscreen.h \
		views/controliqscreen.h \
		views/alertsscreen.h \
		views/pinlockscreen.h \
		views/pinsettingsscreen.h \
		testpanel.h \
		forceresizable.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_testpanel.cpp: testpanel.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include testpanel.h -o moc_testpanel.cpp

moc_forceresizable.cpp: forceresizable.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include forceresizable.h -o moc_forceresizable.cpp

moc_pumpmodel.cpp: models/pumpmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include models/pumpmodel.h -o moc_pumpmodel.cpp

moc_profilemodel.cpp: models/profilemodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include models/profilemodel.h -o moc_profilemodel.cpp

moc_glucosemodel.cpp: models/glucosemodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include models/glucosemodel.h -o moc_glucosemodel.cpp

moc_insulinmodel.cpp: models/insulinmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include models/insulinmodel.h -o moc_insulinmodel.cpp

moc_homescreen.cpp: views/homescreen.h \
		views/graphview.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/homescreen.h -o moc_homescreen.cpp

moc_bolusscreen.cpp: views/bolusscreen.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/bolusscreen.h -o moc_bolusscreen.cpp

moc_profilescreen.cpp: views/profilescreen.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/profilescreen.h -o moc_profilescreen.cpp

moc_optionsscreen.cpp: views/optionsscreen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/optionsscreen.h -o moc_optionsscreen.cpp

moc_graphview.cpp: views/graphview.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/graphview.h -o moc_graphview.cpp

moc_historyscreen.cpp: views/historyscreen.h \
		views/graphview.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/historyscreen.h -o moc_historyscreen.cpp

moc_controliqscreen.cpp: views/controliqscreen.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/controliqscreen.h -o moc_controliqscreen.cpp

moc_alertsscreen.cpp: views/alertsscreen.h \
		controllers/alertcontroller.h \
		models/pumpmodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/alertsscreen.h -o moc_alertsscreen.cpp

moc_pinlockscreen.cpp: views/pinlockscreen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/pinlockscreen.h -o moc_pinlockscreen.cpp

moc_pinsettingsscreen.cpp: views/pinsettingsscreen.h \
		views/pinlockscreen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include views/pinsettingsscreen.h -o moc_pinsettingsscreen.cpp

moc_pumpcontroller.cpp: controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controllers/pumpcontroller.h -o moc_pumpcontroller.cpp

moc_boluscontroller.cpp: controllers/boluscontroller.h \
		models/insulinmodel.h \
		models/glucosemodel.h \
		models/profilemodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controllers/boluscontroller.h -o moc_boluscontroller.cpp

moc_alertcontroller.cpp: controllers/alertcontroller.h \
		models/pumpmodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controllers/alertcontroller.h -o moc_alertcontroller.cpp

moc_profilecontroller.cpp: controllers/profilecontroller.h \
		models/profilemodel.h \
		models/insulinmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include controllers/profilecontroller.h -o moc_profilecontroller.cpp

moc_datastorage.cpp: utils/datastorage.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include utils/datastorage.h -o moc_datastorage.cpp

moc_errorhandler.cpp: utils/errorhandler.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include utils/errorhandler.h -o moc_errorhandler.cpp

moc_controliqalgorithm.cpp: utils/controliqalgorithm.h \
		models/glucosemodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include '/home/student/Documents/3004/test 2.0/moc_predefs.h' -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/student/Documents/3004/test 2.0' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include utils/controliqalgorithm.h -o moc_controliqalgorithm.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_homescreen.h ui_bolusscreen.h ui_profilescreen.h ui_optionsscreen.h ui_historyscreen.h ui_controliqscreen.h ui_pinlockscreen.h ui_alertsscreen.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_homescreen.h ui_bolusscreen.h ui_profilescreen.h ui_optionsscreen.h ui_historyscreen.h ui_controliqscreen.h ui_pinlockscreen.h ui_alertsscreen.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_homescreen.h: views/homescreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/homescreen.ui -o ui_homescreen.h

ui_bolusscreen.h: views/bolusscreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/bolusscreen.ui -o ui_bolusscreen.h

ui_profilescreen.h: views/profilescreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/profilescreen.ui -o ui_profilescreen.h

ui_optionsscreen.h: views/optionsscreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/optionsscreen.ui -o ui_optionsscreen.h

ui_historyscreen.h: views/historyscreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/historyscreen.ui -o ui_historyscreen.h

ui_controliqscreen.h: views/controliqscreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/controliqscreen.ui -o ui_controliqscreen.h

ui_pinlockscreen.h: views/pinlockscreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/pinlockscreen.ui -o ui_pinlockscreen.h

ui_alertsscreen.h: views/alertsscreen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic views/alertsscreen.ui -o ui_alertsscreen.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		views/homescreen.h \
		views/graphview.h \
		views/bolusscreen.h \
		views/profilescreen.h \
		views/optionsscreen.h \
		views/historyscreen.h \
		views/controliqscreen.h \
		views/alertsscreen.h \
		views/pinlockscreen.h \
		views/pinsettingsscreen.h \
		testpanel.h \
		forceresizable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		views/homescreen.h \
		views/graphview.h \
		views/bolusscreen.h \
		views/profilescreen.h \
		views/optionsscreen.h \
		views/historyscreen.h \
		views/controliqscreen.h \
		views/alertsscreen.h \
		views/pinlockscreen.h \
		views/pinsettingsscreen.h \
		testpanel.h \
		forceresizable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

testpanel.o: testpanel.cpp testpanel.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testpanel.o testpanel.cpp

forceresizable.o: forceresizable.cpp forceresizable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forceresizable.o forceresizable.cpp

pumpmodel.o: models/pumpmodel.cpp models/pumpmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pumpmodel.o models/pumpmodel.cpp

profilemodel.o: models/profilemodel.cpp models/profilemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profilemodel.o models/profilemodel.cpp

glucosemodel.o: models/glucosemodel.cpp models/glucosemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glucosemodel.o models/glucosemodel.cpp

insulinmodel.o: models/insulinmodel.cpp models/insulinmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o insulinmodel.o models/insulinmodel.cpp

homescreen.o: views/homescreen.cpp views/homescreen.h \
		views/graphview.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		ui_homescreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o homescreen.o views/homescreen.cpp

bolusscreen.o: views/bolusscreen.cpp views/bolusscreen.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		ui_bolusscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bolusscreen.o views/bolusscreen.cpp

profilescreen.o: views/profilescreen.cpp views/profilescreen.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		ui_profilescreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profilescreen.o views/profilescreen.cpp

optionsscreen.o: views/optionsscreen.cpp views/optionsscreen.h \
		ui_optionsscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsscreen.o views/optionsscreen.cpp

graphview.o: views/graphview.cpp views/graphview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphview.o views/graphview.cpp

historyscreen.o: views/historyscreen.cpp views/historyscreen.h \
		views/graphview.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		ui_historyscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o historyscreen.o views/historyscreen.cpp

controliqscreen.o: views/controliqscreen.cpp views/controliqscreen.h \
		controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h \
		ui_controliqscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controliqscreen.o views/controliqscreen.cpp

alertsscreen.o: views/alertsscreen.cpp views/alertsscreen.h \
		controllers/alertcontroller.h \
		models/pumpmodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		ui_alertsscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alertsscreen.o views/alertsscreen.cpp

pinlockscreen.o: views/pinlockscreen.cpp views/pinlockscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pinlockscreen.o views/pinlockscreen.cpp

pinsettingsscreen.o: views/pinsettingsscreen.cpp views/pinsettingsscreen.h \
		views/pinlockscreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pinsettingsscreen.o views/pinsettingsscreen.cpp

pumpcontroller.o: controllers/pumpcontroller.cpp controllers/pumpcontroller.h \
		models/pumpmodel.h \
		models/profilemodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h \
		utils/controliqalgorithm.h \
		utils/datastorage.h \
		utils/errorhandler.h \
		controllers/alertcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pumpcontroller.o controllers/pumpcontroller.cpp

boluscontroller.o: controllers/boluscontroller.cpp controllers/boluscontroller.h \
		models/insulinmodel.h \
		models/glucosemodel.h \
		models/profilemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boluscontroller.o controllers/boluscontroller.cpp

alertcontroller.o: controllers/alertcontroller.cpp controllers/alertcontroller.h \
		models/pumpmodel.h \
		models/glucosemodel.h \
		models/insulinmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o alertcontroller.o controllers/alertcontroller.cpp

profilecontroller.o: controllers/profilecontroller.cpp controllers/profilecontroller.h \
		models/profilemodel.h \
		models/insulinmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o profilecontroller.o controllers/profilecontroller.cpp

datastorage.o: utils/datastorage.cpp utils/datastorage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datastorage.o utils/datastorage.cpp

errorhandler.o: utils/errorhandler.cpp utils/errorhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o errorhandler.o utils/errorhandler.cpp

controliqalgorithm.o: utils/controliqalgorithm.cpp utils/controliqalgorithm.h \
		models/glucosemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controliqalgorithm.o utils/controliqalgorithm.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_testpanel.o: moc_testpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testpanel.o moc_testpanel.cpp

moc_forceresizable.o: moc_forceresizable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_forceresizable.o moc_forceresizable.cpp

moc_pumpmodel.o: moc_pumpmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pumpmodel.o moc_pumpmodel.cpp

moc_profilemodel.o: moc_profilemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profilemodel.o moc_profilemodel.cpp

moc_glucosemodel.o: moc_glucosemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glucosemodel.o moc_glucosemodel.cpp

moc_insulinmodel.o: moc_insulinmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_insulinmodel.o moc_insulinmodel.cpp

moc_homescreen.o: moc_homescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_homescreen.o moc_homescreen.cpp

moc_bolusscreen.o: moc_bolusscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bolusscreen.o moc_bolusscreen.cpp

moc_profilescreen.o: moc_profilescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profilescreen.o moc_profilescreen.cpp

moc_optionsscreen.o: moc_optionsscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsscreen.o moc_optionsscreen.cpp

moc_graphview.o: moc_graphview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphview.o moc_graphview.cpp

moc_historyscreen.o: moc_historyscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_historyscreen.o moc_historyscreen.cpp

moc_controliqscreen.o: moc_controliqscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controliqscreen.o moc_controliqscreen.cpp

moc_alertsscreen.o: moc_alertsscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alertsscreen.o moc_alertsscreen.cpp

moc_pinlockscreen.o: moc_pinlockscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pinlockscreen.o moc_pinlockscreen.cpp

moc_pinsettingsscreen.o: moc_pinsettingsscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pinsettingsscreen.o moc_pinsettingsscreen.cpp

moc_pumpcontroller.o: moc_pumpcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pumpcontroller.o moc_pumpcontroller.cpp

moc_boluscontroller.o: moc_boluscontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_boluscontroller.o moc_boluscontroller.cpp

moc_alertcontroller.o: moc_alertcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_alertcontroller.o moc_alertcontroller.cpp

moc_profilecontroller.o: moc_profilecontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_profilecontroller.o moc_profilecontroller.cpp

moc_datastorage.o: moc_datastorage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datastorage.o moc_datastorage.cpp

moc_errorhandler.o: moc_errorhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_errorhandler.o moc_errorhandler.cpp

moc_controliqalgorithm.o: moc_controliqalgorithm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controliqalgorithm.o moc_controliqalgorithm.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/tslimx2simulator/bin || mkdir -p $(INSTALL_ROOT)/opt/tslimx2simulator/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/tslimx2simulator/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/tslimx2simulator/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/tslimx2simulator/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/tslimx2simulator/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

